<?php
/**
 * Language labels for database tables/fields belonging to extension "wec_devo"
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tt_content.list_type_pi1" => "WEC Devotional Journal",

		"tx_wecdevo_content" => "Devo Content",
		"tx_wecdevo_content.content" => "Content",
       	"tx_wecdevo_content.intro" => "Intro",
	    "tx_wecdevo_content.scripture_ref" => "Scripture Reference",
	    "tx_wecdevo_content.scripture" => "Scripture",
	    "tx_wecdevo_content.questions" => "Questions",
	    "tx_wecdevo_content.prayer" => "Prayer",
	    "tx_wecdevo_content.application" => "Application",
	    "tx_wecdevo_content.end_content" => "End Content",
		"tx_wecdevo_content.type" => "Type of content",
			"tx_wecdevo_content.type.I.0" => "HTMLTEXT",
			"tx_wecdevo_content.type.I.1" => "PAGE",
			"tx_wecdevo_content.type.I.2" => "FORUM",
			"tx_wecdevo_content.type.I.5" => "HEADER",
		"tx_wecdevo_content.section" => "Section to display",
			"tx_wecdevo_content.section_all" => "All",
		"tx_wecdevo_content.audio_file" => "Audio file name",
		"tx_wecdevo_content.video_file" => "Video file name",

		"tx_wecdevo_section" => "Devo Section",
		"tx_wecdevo_section.name" => "Name of Section",
		"tx_wecdevo_section.position" => "Position In Interface",
		"tx_wecdevo_section.start_at" => "Start At This Interface?",
			"tx_wecdevo_section.start_at.I.0" => "no",
			"tx_wecdevo_section.start_at.I.1" => "default",
			"tx_wecdevo_section.start_at.I.2" => "startweekly",
		"tx_wecdevo_section.time_period" => "Time Period For Content",
		"tx_wecdevo_section.time_period.I.0" => "daily",
		"tx_wecdevo_section.time_period.I.1" => "weekly",
		"tx_wecdevo_section.time_period.I.2" => "monthly",
		"tx_wecdevo_section.time_period.I.3" => "yearly",
		"tx_wecdevo_section.time_period.I.4" => "always",

		"tx_wecdevo_section.template" 	=> "Name of Template",
		"tx_wecdevo_section.has_comments" => "If Page Has Comments",
		"tx_wecdevo_section.subscriber_only" => "Only Subscriber Can Access",
        "tx_wecdevo_section.data_uid" 	=> "Data UID (for duplicating cat.)",
        "tx_wecdevo_section.next_sequence" 	=> "Next In Sequence UID (for following)",

		"tx_wecdevo_journal" 			=> "Devo Journal",
		"tx_wecdevo_journal.owner_userid" => "User ID Of Owner",
		"tx_wecdevo_journal.entry" 		=> "Entry to Journal",
		"tx_wecdevo_journal.post_date" 	=> "Date Posted (YYYY-MM-DD)",

		"tx_wecdevo_users" 				=> "Devo User",
		"tx_wecdevo_users.user_uid" 	=> "User Typo3 UID",
		"tx_wecdevo_users.email" 		=> "Email of User",
		"tx_wecdevo_users.lastlogin_date" => "Last Login Date",
		"tx_wecdevo_users.receive_by_email" => "Receive By Email?",
		"tx_wecdevo_users.how_paid" 	=> "How Paid (if subscription)",
		"tx_wecdevo_users.paidto_date" 	=> "What Date Paid To",
		"tx_wecdevo_users.usergroup"	=> "Usergroup",
		"tx_wecdevo_users.misc" 		=> "Misc Tracking Field",

		"tx_wecdevo_topics" 			=> "Devo Topic",
		"tx_wecdevo_topics.topic" 		=> "Topic Name",
		"tx_wecdevo_topics.show_date" 	=> "When This Is Shown (start date)",
		"tx_wecdevo_topics.num" 		=> "Which Position This Is In Sequence",

		'wec_devo.pi_flexform.sheet_main' 	 	=> 'Main',
		'wec_devo.pi_flexform.template_file' 	=> 'Template File:',
		'wec_devo.pi_flexform.commentsPID' 		=> 'Comments Page ID (optional):',
		'wec_devo.pi_flexform.previewPID' 		=> 'Preview Page ID (optional):',

		'wec_devo.pi_flexform.sheet_display' 	=> 'Display',
		'wec_devo.pi_flexform.allowPaging' 		=> 'Allow Paging Control?',
		'wec_devo.pi_flexform.allowTextSize' 	=> 'Allow Text Size Control?',
		'wec_devo.pi_flexform.useNextArrow' 	=> 'Show Next Arrow (uses "next in sequence" from section)?',

		'wec_devo.pi_flexform.sheet_journal' 	=> 'Journal',
		'wec_devo.pi_flexform.hasJournal'	 	=> 'Allow Journal?',
		'wec_devo.pi_flexform.allowPrintJournal' => 'Allow To Print Journal?',
		'wec_devo.pi_flexform.journal_extrabuttons' => 'Extra Journal Button Code (Javascript)',
		'wec_devo.pi_flexform.rte_code' 		=> 'Special Code for RTE (JavaScript only)',

		'wec_devo.pi_flexform.sheet_audiovideo' 	=> 'Audio/Video',
		'wec_devo.pi_flexform.hasAudio' 	 	=> 'Has Audio?',
		'wec_devo.pi_flexform.hasVideo' 	 	=> 'Has Video?',
		'wec_devo.pi_flexform.audioplayer_code' => 'Code for Audio Player (JavaScript/HTML)',
		'wec_devo.pi_flexform.audiofile_autoformat' => 'Autoformat Audio Filenames (1|code|2|code2...)',
		'wec_devo.pi_flexform.videoplayer_code' => 'Code for Video Player (JavaScript/HTML)',
		'wec_devo.pi_flexform.videofile_autoformat' => 'Autoformat Video Filenames (1|code|2|code2...)',

		'wec_devo.pi_flexform.sheet_dates' 	=> 'Dates',
		'wec_devo.pi_flexform.date_offset_orig'	=> 'Date Offset Original "MM-DD-YYYY" (Weekly)',
		'wec_devo.pi_flexform.date_offset_cur'	=> 'Date Offset New Start "MM-DD-YYYY" (Weekly)',
		'wec_devo.pi_flexform.devo_firstdate'	=> 'Start Devo Date "MM-DD-YYYY" (for calendar)',
		'wec_devo.pi_flexform.devo_lastdate'	=> 'Last Devo Date "MM-DD-YYYY" (for calendar)',
		'wec_devo.pi_flexform.date_format'		=> 'PHP date format for ###DATE### (see php.net/date)',

		'wec_devo.pi_flexform.sheet_admin' 		=> 'Administrator',
		'wec_devo.pi_flexform.administrator_list' => 'Admin List- UID or username (sep. by comma)',
	),
	"nl" => Array (
		'tt_content.list_type_pi1' => 'WEC godsdienstig dagboek (Devo)',
		'tx_wecdevo_content' => 'Devo inhoud',
		'tx_wecdevo_content.content' => 'Inhoud',
		'tx_wecdevo_content.intro' => 'Intro',
		'tx_wecdevo_content.scripture_ref' => 'Schrift Reference',
		'tx_wecdevo_content.scripture' => 'Schrift',
		'tx_wecdevo_content.questions' => 'Vragen',
		'tx_wecdevo_content.prayer' => 'Bidder',
		'tx_wecdevo_content.application' => 'Toepassing',
		'tx_wecdevo_content.end_content' => 'Eind inhoud',
		'tx_wecdevo_content.type' => 'Soort inhoud',
		'tx_wecdevo_content.type.I.0' => 'HTMLTEXT',
		'tx_wecdevo_content.type.I.1' => 'PAGE',
		'tx_wecdevo_content.type.I.2' => 'FORUM',
		'tx_wecdevo_content.type.I.5' => 'HEADER',
		'tx_wecdevo_content.section' => 'Sectie voor de interface',
		'tx_wecdevo_content.section_all' => 'geen',
		'tx_wecdevo_content.audio_file' => 'Audio bestandsnaam',
		'tx_wecdevo_content.video_file' => 'Video bestandsnaam',
		'tx_wecdevo_section' => 'Devo sectie',
		'tx_wecdevo_section.name' => 'Sectie naam',
		'tx_wecdevo_section.position' => 'Plaats in de interface',
		'tx_wecdevo_section.start_at' => 'Beginnen met deze interface?',
		'tx_wecdevo_section.start_at.I.0' => 'nee',
		'tx_wecdevo_section.start_at.I.1' => 'standaard',
		'tx_wecdevo_section.start_at.I.2' => 'wekelijkse start',
		'tx_wecdevo_section.time_period' => 'Tijdsperiode voor de inhoud',
		'tx_wecdevo_section.time_period.I.0' => 'dagelijks',
		'tx_wecdevo_section.time_period.I.1' => 'wekelijks',
		'tx_wecdevo_section.time_period.I.2' => 'maandelijks',
		'tx_wecdevo_section.time_period.I.3' => 'jaarlijks',
		'tx_wecdevo_section.time_period.I.4' => 'altijd',
		'tx_wecdevo_section.template' => 'Naam van de sjabloon',
		'tx_wecdevo_section.has_comments' => 'Als de pagina opmerkingen heeft',
		'tx_wecdevo_section.subscriber_only' => 'Alleen een toegang voor abonnees',
		'tx_wecdevo_section.data_uid' => 'Data UID (voor categorie dupliceren))',
		'tx_wecdevo_section.next_sequence' => 'Volgende in de rij UID (voor vervolg)',
		'tx_wecdevo_journal' => 'Devo dagboek',
		'tx_wecdevo_journal.owner_userid' => 'User ID van de eigenaar',
		'tx_wecdevo_journal.entry' => 'Toegang tot het dagboek',
		'tx_wecdevo_journal.post_date' => 'Postingsdatum (JJJJ-MM-DD)',
		'tx_wecdevo_users' => 'Devo gebruiker',
		'tx_wecdevo_users.user_uid' => 'TYPO3 gebruikers UID',
		'tx_wecdevo_users.email' => 'Email van de gebruiker',
		'tx_wecdevo_users.lastlogin_date' => 'Laatste inlogdatum',
		'tx_wecdevo_users.receive_by_email' => 'Per email ontvangen?',
		'tx_wecdevo_users.how_paid' => 'Hoe betalen (bij een abonnement)',
		'tx_wecdevo_users.paidto_date' => 'Tot welke datum betaald',
		'tx_wecdevo_users.usergroup' => 'Gebruikersgroep',
		'tx_wecdevo_users.misc' => 'Diversen veld',
		'tx_wecdevo_topics' => 'Devo onderwerp',
		'tx_wecdevo_topics.topic' => 'Onderwerp naam',
		'tx_wecdevo_topics.show_date' => 'Wanneer wordt dit getoond (start datum)',
		'tx_wecdevo_topics.num' => 'Welke plaats dit is in de rij',

		'wec_devo.pi_flexform.sheet_main' => 'Hoofd',
		'wec_devo.pi_flexform.template_file' => 'Sjabloon bestand:',
		'wec_devo.pi_flexform.commentsPID' => 'ID van de opmerkingen pagina (optioneel):',
		'wec_devo.pi_flexform.previewPID' => 'ID van de voorschouw pagina (optioneel):',

		'wec_devo.pi_flexform.sheet_display' 		=> 'Display',
		'wec_devo.pi_flexform.allowPagingTextSize' => 'Paginering/tekstgroote wijzigen toestaan?',
		'wec_devo.pi_flexform.useNextArrow' => 'Toon volgende pijl (gebruik "volgende in de rij")?',

		'wec_devo.pi_flexform.sheet_journal' 		=> 'Dagboek',
		'wec_devo.pi_flexform.hasJournal' => 'Dagboek toestaan?',
		'wec_devo.pi_flexform.allowPrintJournal' => 'Printen van dagboek toestaan?',
		'wec_devo.pi_flexform.journal_extrabuttons' => 'Code voor knop Extra dagboek (javascript)',
		'wec_devo.pi_flexform.rte_code' => 'Speciale code voor de RTE (alleen Javascript)',

		'wec_devo.pi_flexform.sheet_audiovideo' 		=> 'Audio/Video',
		'wec_devo.pi_flexform.hasAudio' => 'Heeft audio?',
		'wec_devo.pi_flexform.hasVideo' => 'Heeft video?',
		'wec_devo.pi_flexform.audioplayer_code' => 'Code voor audio speler (Javascript/HTML)',
		'wec_devo.pi_flexform.audiofile_autoformat' => 'Zelf-formateren van de audio bestandsnamen (1|code1|2|code2...)',
		'wec_devo.pi_flexform.videoplayer_code' => 'Code voor video speler (Javascript/HTML)',
		'wec_devo.pi_flexform.videofile_autoformat' => 'Zelf-formateren van de video bestandsnamen (1|code1|2|code2...)',

		'wec_devo.pi_flexform.sheet_dates' 		=> 'Datum',
		'wec_devo.pi_flexform.date_offset_orig' => 'Datum verschil origineel "MM-DD-JJJJ (Wekelijks)"',
		'wec_devo.pi_flexform.date_offset_cur' => 'Datum verschil nieuwe start "MM-DD-JJJJ (Wekelijks)"',
		'wec_devo.pi_flexform.devo_firstdate' => 'Datum start Devo "MM-DD-JJJJ" (voor de kalender)',
		'wec_devo.pi_flexform.devo_lastdate' => 'Laatste Devo datum "MM-DD-JJJJ" (voor de kalender)',
		'wec_devo.pi_flexform.date_format' => 'PHP datum formaat voor ###DATE### (zie php.net/date)',

		'wec_devo.pi_flexform.sheet_admin' 		=> 'Administrator',
		'wec_devo.pi_flexform.administrator_list' => 'Lijst met admins - UID of gebruikersnaam (komma gescheiden)',

	),
);
?>